### PR TITLE
Use braces with all blocks

### PR DESCRIPTION
**Pull request by thepatrick**
## What

```javascript
// before
// good
if (test) return false;

//after
// bad
if (test) return false;
```

## Why

1. Consistency with the current code base
2. Braces are good

### CODE REVIEW

**Comment by manasdpradhan** [comment]
+1!!

**Comment by jraoult** [comment]
+1

**Comment by luma** [comment]
+1

**Comment by jeffswartz** [comment]
+1!!!

**Comment by leahciMic** [comment]
+100

**Pull request merged**
